baseURL = 'https://intelligeneer.github.io/pospal-training/'
languageCode = 'en-us'
title = 'ğŸ–¥ï¸ Pospal Training Video'
theme = 'paper'

enableInlineShortcodes = 'true' #å…è®¸å†…è”çŸ­ç 
enableEmoji = 'true'   #å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT = 'true' #å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage = 'true' #è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

buildDrafts = 'false'
buildFuture = 'false'
buildExpired = 'false'

[menu]
[[menu.main]]
identifier = "about"
name = "About Us"
url = "/about/"
weight = 10


[params]
author = "Intelligeneer Soltuion"
description = "There need to be add description"
#twitter = ''                # twitter.com/YOUR_TWITTER_ID
#   github = ''                  # github.com/YOUR_GITHUB_ID
instagram = 'ada_pay_'            # instagram.com/YOUR_INSTAGRAM_ID
avatar = "https://www.intelligeneer.com/cdn/shop/files/Screen_Shot_2022-04-28_at_11.08.37_AM.png?v=1651108130"

[taxonomies]
tag = "tags"

